### ISSUE TITLE
Грешка при повторно попълване

### ISSUE THREAD

**Issue by Milenkov** [riverside/friendurl#3]
Здравейте,

Много полезен скрипт, благодаря на създателите :)
Но,
Забелязах следният бъг.

Ако имаме няколко двойки, които се попълват, след като поредно сме попълнили полетата, ако се върнем на първото поле за корекция, текста не се появява в неговото референтно поле а в референтното поле на последно попълваното преди него.

![1stok](https://cloud.githubusercontent.com/assets/13676340/9109238/cc267100-3c3c-11e5-8f40-abdafc6bfa3e.jpg)
![2ndbug](https://cloud.githubusercontent.com/assets/13676340/9109239/cc2a52ca-3c3c-11e5-853f-07ebd1c0c04e.jpg)

Надявам се да съм бил ясен :)

Поздрави!

**Comment by riverside** [comment]
Fixed in v1.7.1

**Comment by Milenkov** [comment]
Супер, благодаря и успех!
